name: Docker Image CI

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: pre-step
      shell: bash
      run: |
        echo "release-version=${{ github.ref }}" >> $GITHUB_ENV
        echo "commit-sha=${{ github.sha }}" >> $GITHUB_SHA
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: jfcal/data-quality-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: ${{ github.event_name != 'schedule' }}
        snapshot: true
        tags: "latest"
        workdir: .
        platforms: linux/amd64,linux/arm64

